BOARDCPPSRC =  $(BOARD_DIR)/board_configuration.cpp \
    $(BOARD_DIR)/default_tune.cpp \


BOARDINC += $(BOARD_DIR)/generated/controllers/generated

# defines SHORT_BOARD_NAME
include $(BOARD_DIR)/meta-info.env

# reduce memory usage monitoring
DDEFS += -DRAM_UNUSED_SIZE=100
IS_STM32F429 = yes
# assign critical LED to a non-existent pin if you do not have it on your board
DDEFS += -DLED_CRITICAL_ERROR_BRAIN_PIN=Gpio::E3

DDEFS += -DEFI_SOFTWARE_KNOCK=FALSE
DDEFS += -DEFI_ENGINE_CONTROL = FALSE
DDEFS += -DEFI_BOOST_CONTROL = FALSE
DDEFS += -DEFI_LAUNCH_CONTROL = FALSE
DDEFS += -DEFI_ANTILAG_SYSTEM = FALSE
DDEFS += -DEFI_DYNO_VIEW = FALSE
DDEFS += -DEFI_TOOTH_LOGGER = FALSE
DDEFS += -DEFI_HPFP = FALSE
DDEFS += -DEFI_HD_ACR = FALSE
DDEFS += -DEFI_RTC = FALSE
DDEFS += -DEFI_ALTERNATOR_CONTROL = FALSE
DDEFS += -DEFI_VVT_PID = FALSE
DDEFS += -DEFI_SHAFT_POSITION_INPUT = FALSE
DDEFS += -DEFI_IDLE_CONTROL = FALSE
DDEFS += -DEFI_IDLE_PID_CIC = FALSE
DDEFS += -DEFI_ENGINE_EMULATOR = FALSE
DDEFS += -DLUA_USER_HEAP = 50000
DDEFS += -DEFI_ENGINE_SNIFFER = FALSE
DDEFS += -DEFI_ELECTRONIC_THROTTLE_BODY = FALSE
DDEFS += -DEFI_MALFUNCTION_INDICATOR = FALSE
